NAME =   Sed_is_for_losers

SRCS = main.cpp \

OBJSRCS = $(SRCS:.cpp=.o)

jean = g++

CFLAGS = -Wall -Wextra -Werror #-std=c++98

$(NAME): $(OBJSRCS)
	$(jean) $(CFLAGS) $(OBJSRCS) -o $(NAME)

all: $(NAME)

.cpp.o:
	$(jean) $(CFLAGS) -c $<

clean:
	rm -f $(OBJSRCS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all re clean fclean
